spring:
  application:
    name: eureka-client

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Eureka Server
    register-with-eureka: true
    fetch-registry: true
